# fly.toml app configuration file generated for billowing-bush-7931 on 2023-04-27T05:50:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-bush-7931"
primary_region = "nrt"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_DEBUG = "false"
  APP_ENV = "production"
  APP_NAME = "Laravel"
  APP_URL = "https://billowing-bush-7931.fly.dev"
  DB_CONNECTION = "pgsql"
  DB_DATABASE = "postgres"
  DB_HOST = "db.psdktaaqrbxdiqpynmmz.supabase.co"
  DB_PORT = "5432"
  DB_USERNAME = "postgres"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
